[package]
name = "goldenrod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "examples/hello-world"
]

[dependencies]
gl = { version = "0.14" }
nvg = "0.5"
log = "0.4"